import React, { useState, useCallback, useEffect } from 'react';
import EntryTopFrame from './entry/EntryTopFrame';
import EntryItemsTable from './entry/EntryItemsTable';
import api from '../utils/api';
import './PurchaseCreationPage.css';

const PurchaseCreationPage = () => {
  const [formData, setFormData] = useState({
    date: new Date().toISOString().slice(0, 10),
    inv_no: '',
    supplier: '',
    pay_type: 'Credit',
    type: 'Urad',
    godown: '',
    remarks: ''
  });
  const [rows, setRows] = useState([{}]);

  const handleFormChange = useCallback((changeEvent) => {
    setFormData(prev => ({ ...prev, [changeEvent.target.name]: changeEvent.target.value }));
  }, []);

  const handleTableChange = useCallback((index, field, value) => {
    setTableData(prev => {
      let updated;
      if (field === '__batch__' && typeof value === 'object') {
        updated = prev.map((row, i) => i === index ? { ...row, ...value } : row);
      } else {
        updated = prev.map((row, i) => 
          i === index ? { ...row, [field]: field === 'item_name' ? value : parseFloat(value) || 0 } : row
        );
      }
      // Recalculate
      return updated.map(row => {
        const totalWt = (row.weight || 0) * (row.qty || 0);
        let amount = (row.qty || 0) * (row.rate || 0);
        amount -= (amount * (row.disc || 0)) / 100;
        amount += (amount * (row.tax || 0)) / 100;
        return { ...row, totalWt, amount };
      });
    });
  }, []);

const addRow = useCallback(() => {
  const newSno = tableData.length + 1;
  setTableData(prev => [...prev, {
    sno: newSno,
    item_name: '',
    lot_no: '',
    weight: 0,
    qty: 0,
    totalWt: 0,
    rate: 0,
    disc: 0,
    tax: 0,
    amount: 0
  }]);
}, [tableData.length]); // Lot auto-generated by EntryItemsTable lotMode="auto"

  const deleteRow = useCallback((index) => {
    setTableData(prev => prev.filter((_, i) => i !== index));
  }, []);

  const totalQty = tableData.reduce((sum, row) => sum + row.qty, 0)
  const totalWeight = tableData.reduce((sum, row) => sum + row.totalWt, 0)
  const totalAmount = tableData.reduce((sum, row) => sum + row.amount, 0)

  useEffect(() => {
    if (rows.length === 0) {
      setRows([{}]);
    }
  }, []);

  const handleSubmit = async (e) => {
    e.preventDefault()

    // NEW: Calculate totals
    const totalQty = tableData.reduce((sum, row) => sum + row.qty, 0);
    const totalWeight = tableData.reduce((sum, row) => sum + row.totalWt, 0);
    const totalAmount = tableData.reduce((sum, row) => sum + row.amount, 0);

    const payload = {
      formData,
      items: tableData,
      totals: {
        totalQty,
        totalWeight,
        totalAmount,
        baseAmount: totalAmount,
        discAmount: 0,
        taxAmount: 0,
        netAmount: totalAmount,
        grandTotal: totalAmount
      }
    };

    console.log('Submitting Purchase:', payload);

    try {
      // NEW: Use Tauri API instead of fetch
      const result = await api.createPurchase(formData, tableData, payload.totals);
      if (result.success) {
        alert('Purchase saved successfully!');
        // Reset form
        setFormData({
          sno: (parseInt(formData.sno) || 0) + 1 + '',
          date: new Date().toISOString().slice(0, 10),
          invNo: '',
          supplier: '',
          payType: 'Credit',
          type: 'Urad',
          godown: '',
          remarks: ''
        });
        setTableData([]);
      } else {
        alert(`Error: ${result.message || 'Save failed'}`);
      }
    } catch (error) {
      alert('Save error: ' + error.message);
      console.error('Purchase save error:', error);
    }
  };

  return (
    <div className="purchase-entry">
      <div className="screen-title">Purchase Entry</div>
      
      {/* NEW: EntryTopFrame with master dropdowns */}
      <EntryTopFrame
        fields={[
          { name: 'date', label: 'Date', type: 'date' },
          { name: 'inv_no', label: 'Inv No', type: 'text' },
          { name: 'supplier', label: 'Supplier', type: 'masterSelect', masterType: 'suppliers' },
          { name: 'pay_type', label: 'Pay Type', type: 'select', options: [
            { value: 'Credit', label: 'Credit' },
            { value: 'Cash', label: 'Cash' }
          ] },
          { name: 'type', label: 'Type', type: 'text' },
          { name: 'godown', label: 'Godown', type: 'masterSelect', masterType: 'godowns' },
          { name: 'remarks', label: 'Remarks', type: 'textarea' }
        ]}
        data={formData}
        onChange={handleFormChange}
        columns={3}
      />
      
      {/* NEW: EntryItemsTable with masters + auto-lot */}
        <EntryItemsTable
          sectionTitle="Items"
          columns={[
            { key: 's_no', title: 'S.No', readOnly: true },
            { key: 'item_name', title: 'Item', type: 'masterSelect', masterType: 'items' },
            // 🔥 AUTO LOT FIXED: simple lot_no - EntryItemsTable forces readonly input via lotMode="auto"
            { key: 'lot_no', title: 'Lot No' },
            { key: 'weight', title: 'Weight', type: 'number' },
            { key: 'qty', title: 'Qty', type: 'number' },
            { key: 'total_wt', title: 'Total Wt', readOnly: true },
            { key: 'rate', title: 'Rate', type: 'number' },
            { key: 'disc', title: 'Disc %', type: 'number' },
            { key: 'tax', title: 'Tax %', type: 'number' },
            { key: 'amount', title: 'Amount', readOnly: true }
          ]}
          data={rows}
          onRowChange={handleTableChange}
          onAddRow={addRow}
          onDeleteRow={deleteRow}
          lotMode="auto"
          itemColumnKey="item_name"
          taxType="Exclusive"
          taxRate={18}
          editable={true}
          showActions={true}
        />
      />
      
      <div className="totals-section">
        <div className="totals-left">
          <div className="totals-box">
            <div>Total Qty: {totalQty.toFixed(3)}</div>
            <div>Total Weight: {totalWeight.toFixed(3)}</div>
            <div>Total Amount: ₹{totalAmount.toFixed(2)}</div>
          </div>
        </div>
        <div className="save-section">
          <button type="submit" className="save-btn">💾 Save Purchase</button>
        </div>
      </div>
    </div>
  </form>
  );
};

export default PurchaseCreationPage
